### ISSUE TITLE
GOED Logo

### ISSUE THREAD

**Issue by stdavis** [agrc/recreate-web#16]
It either needs to go away or be made to look nice on top of the background image.

**Comment by stdavis** [comment]
@brigsz: Should we just remove the GOED logo and wait for them to ask for it? Or is it a requirement?

**Comment by brigsz** [comment]
@stdavis  yah, Tom Adams the director of the Outdoor Recreation Office actually asked for it to be there

**Comment by stdavis** [comment]
Good to know, thanks.

**Comment by stdavis** [comment]
I switched the text to white in this commit: https://github.com/agrc/recreate-web/commit/ed3f402259f8181edd27ec8b068b90a4ddd2500d.

![image](https://user-images.githubusercontent.com/1326248/36686301-33507bfa-1ae3-11e8-93a8-00d5f4eaa881.png)

Closing for now.
