### ISSUE TITLE
multiple points link to the same park

### ISSUE THREAD

**Issue by brigsz** [agrc/recreate-web#23]
I am in the app, click on a park- the water tank North and east of our office on the hill , it takes me to a park Raspberry patch and Yacht Drive.  Then that window just closes automatically.  It turns out that Park is in Rich County adjacent to Bear Lake

**Comment by stdavis** [comment]
I believe that this is no longer an issue since we switched the parks layer to be national & state parks and monuments. Let me know if you see otherwise, @brigsz.
