### ISSUE TITLE
Trail Details Link

### ISSUE THREAD

**Issue by stdavis** [agrc/recreate-web#3]
Wire up link to visitutah.com. It's hardcoded to the Chinle trail for now.

**Comment by brigsz** [comment]
I have put this as a priority, however it is only valid for the ones that exist, and it will only probably be for ones around Zion National Park.  Well, those are the ones that will have the map embedded from Outer Spatial. Not sure what other trails are out there

**Comment by stdavis** [comment]
There isn't any data for this yet. They haven't put any URLs in the routes table.

**Comment by stdavis** [comment]
This was closed with: b3d02b10921bb3da0b7c9fb78d6e8510685ceaeb
